name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build-mode: ["Release 64-Bit", "Release 64-Bit O4 AVX2"]
    steps:
    - uses: actions/checkout@v2
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3.0.2
      with:
        lazarus-version: "dist"
    - name: Download Lazarus 32bit addon
      id: lazarus32
      uses: suisei-cn/actions-download-file@v1
      with:
        url: https://cfhcable.dl.sourceforge.net/project/lazarus/Lazarus%20Windows%2064%20bits/Lazarus%202.0.10/lazarus-2.0.10-fpc-3.2.0-cross-i386-win32-win64.exe
        target: ${{ runner.temp }}/
    - name: Install Lazarus 32bit addon
      run: ${{ runner.temp }}/${{ steps.lazarus32.outputs.filename }} /VERYSILENT /DIR=${{ runner.temp }}/lazarus
    - name: Build level2
      run: lazbuild -B "Cheat Engine/sfx/level2/standalonephase2.lpi" --cpu=i386
    - name: Build the Main Application
      run: lazbuild -B "Cheat Engine/cheatengine.lpi" --cpu=x86_64 --build-mode="${{ matrix.build-mode }}"
    - name: Upload the Application
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.build-mode }}
        path: "Cheat Engine/bin"
