name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3.0.16
      with:
        lazarus-version: "dist"
    - name: Build the Main Application
      run: lazbuild -B "Cheat Engine/cheatengine.lpi"
    - name: Upload the Application
      uses: actions/upload-artifact@v2
      with:
        name: cheatengine
        path: "Cheat Engine/bin"
